// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpTD5zbioElrfcpdLlhsBO_IzQqJEuzfY',
    appId: '1:803005100742:web:532c48c6fc126188ad9dc7',
    messagingSenderId: '803005100742',
    projectId: 'fir-pushnotification-dd17d',
    authDomain: 'fir-pushnotification-dd17d.firebaseapp.com',
    storageBucket: 'fir-pushnotification-dd17d.appspot.com',
    measurementId: 'G-BX4PSB2NNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgwSQGnUmPd-OwZOruaLOK43zhEW1wfQo',
    appId: '1:803005100742:android:07b345d9c4b45483ad9dc7',
    messagingSenderId: '803005100742',
    projectId: 'fir-pushnotification-dd17d',
    storageBucket: 'fir-pushnotification-dd17d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeK9dlRxV8T6ZIf8B-sEey6jlox7zXeZI',
    appId: '1:803005100742:ios:6e62ca856180259fad9dc7',
    messagingSenderId: '803005100742',
    projectId: 'fir-pushnotification-dd17d',
    storageBucket: 'fir-pushnotification-dd17d.appspot.com',
    iosClientId: '803005100742-g3rfc38lrjema0lkioi0u9rq2simrsjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.geolocalizacionamd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeK9dlRxV8T6ZIf8B-sEey6jlox7zXeZI',
    appId: '1:803005100742:ios:6e62ca856180259fad9dc7',
    messagingSenderId: '803005100742',
    projectId: 'fir-pushnotification-dd17d',
    storageBucket: 'fir-pushnotification-dd17d.appspot.com',
    iosClientId: '803005100742-g3rfc38lrjema0lkioi0u9rq2simrsjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.geolocalizacionamd',
  );
}
